### ISSUE TITLE
White screen and disappearing code

### ISSUE THREAD

**Issue by Brum-Brum** [Hexer10/Spedit#11]
When you drag the window, a white screen appears. After the window has been put down  code disappears.
https://gyazo.com/40aae66f116c97fb20974952cbaf9441

**Comment by Hexer10** [comment]
Thanks for submitting the issue, I'll try to figure out how to fix the issue

**Comment by Hexer10** [comment]
I'm reopening this since even tough now you can pop out the tab and edit it, you can't close the new tab.

**Comment by Hexer10** [comment]
Now it should be fixed, if you still find any error regarding this, please reopen this issue.
(The fix is available starting from 1.3.5.1)
