### ISSUE TITLE
Colouring

### ISSUE THREAD

**Issue by Yamakashi** [Hexer10/Spedit#14]
You can add colouring methodmap "Function".

**Comment by Hexer10** [comment]
Do you mean a new slider in the settings page? for the methodmaps functions?

**Comment by Yamakashi** [comment]
No, I thought about something like this:
Function class = GetFunctionByName(g_hClassSystem[g_iClass[client]], "Dr_OnClassDisabled");
and you can coulour word "Function".

**Comment by Hexer10** [comment]
Yeah, for sure

**Comment by Hexer10** [comment]
Done with https://github.com/Hexer10/Spedit/commit/d91d29315220134a7cf71dd60e4297010b541991 
Available starting from version `1.3.4.5`
