### ISSUE TITLE
Auto close brackets doesn't use spaces

### ISSUE THREAD

**Issue by Bara** [Hexer10/Spedit#5]
My settings:
https://i.imgur.com/YL4dp4s.png

Here's a gif as example what I mean:
https://i.imgur.com/xJRZ4K5.gif

**Comment by Hexer10** [comment]
With the latest version (1.3.5.1) this should be fixed, now all tabs (`\t`) should be replaced with spaces if the checkbox is selected, the number of spaces is the same as the indentation size

**Comment by Bara** [comment]
It looks good so far.
